tasm /la /zi aspira1.asm
tasm /la /zi dibujar.asm
tasm /la /zi borrar.asm
tasm /la /zi b_caja.asm
tasm /la /zi d_caja.asm
tasm /la /zi esperar.asm
tasm /la /zi naleat.asm
tasm /la /zi encesta.asm
tasm /la /zi movasp.asm
tasm /la /zi movbol.asm
tasm /la /zi ponerch.asm
tasm /la /zi rotarc.asm
tasm /la /zi menu.asm
tlink /v /m aspira1 dibujar borrar b_caja d_caja esperar naleat encesta movasp movbol ponerch rotarc menu
